apiVersion: v1
kind: ConfigMap
metadata:
  name: database-config
  namespace: campus-events
  labels:
    app: campus-events
    component: config
data:
  DB_HOST: "campus-events-dev-db.ckxuk4eosxj9.us-east-1.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "campusevents"
  DB_SSL_MODE: "require"
