apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: campus-events

resources:
  # ConfigMaps
  - configmap-database.yaml
  - configmap-app.yaml
  
  # Frontend
  - frontend/deployment.yaml
  - frontend/service.yaml
  - frontend/hpa.yaml
  
  # Events API
  - events-api/deployment.yaml
  - events-api/service.yaml
  - events-api/hpa.yaml
  
  # Notification Service
  - notification-service/deployment.yaml
  - notification-service/service.yaml
  - notification-service/hpa.yaml

commonLabels:
  project: campus-events
  managed-by: kustomize
