apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: events-api-metrics
  namespace: campus-events
  labels:
    app: events-api
    release: kube-prom-stack
spec:
  selector:
    matchLabels:
      app: events-api
  endpoints:
  - port: http
    interval: 30s
    path: /metrics
    scheme: http
  namespaceSelector:
    matchNames:
    - campus-events
